version: "3.8"

x-default-logging: &default_logging
  driver: ${ENV_LOG_DRIVER:-json-file}
  options:
    max-size: ${ENV_LOG_MAX_SIZE:-100m}
    max-file: ${ENV_LOG_MAX_FILE:-1}

networks:
  default:
    name: "poweradmin_net"
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

services:
  nginx:
    image: nginx:1.21.4
    container_name: poweradmin_nginx
    restart: unless-stopped
    command: [ "nginx", "-g", "daemon off;" ]
    healthcheck:
      test: curl -o /dev/null -s -w "%{http_code}\n" 127.0.0.1/healthcheck | grep -q "200" || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
    ports:
      - "80:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro"
    networks:
      default:
        aliases:
          - nginx
    logging: *default_logging

  php:
    image: mottor/poweradmin
    container_name: poweradmin_php
    restart: unless-stopped
    build:
      context: .
    networks:
      default:
        aliases:
          - php
    logging: *default_logging